Repository Quick-Project/BMTI-DLink, pull requests merged in 2022-10, with the labels that each got.

#28 🥃 fix : 더미데이터, 버튼 높이, 컬러코드 수정
  src/App.js
  src/assets/data/dummyData.js
  src/components/Question.js
Labels: 🚨 BugFix

#29 🍷 docs: Add ShareComponent bottom margin 50px, ppack ShareComponent align items center
  package-lock.json
  src/pages/Ppak.js
  src/pages/ResultScreen.js
Labels: 📄 Docs

#30 🍹 style : 로딩 버그, vw와 vh 수정
  src/App.js
  src/components/Loading.js
  src/components/Question.js
  src/components/SocialShare.js
Labels: 🚨 BugFix

#32 🥃 fix : Social Btn css,URL 수정
  src/components/SocialComponents/FaceBook.js
  src/components/SocialComponents/Kakao.js
  src/components/SocialComponents/LinkCopy.js
  src/components/SocialComponents/Twitter.js
  src/components/SocialShare.js
  src/pages/Ppak.js
  src/pages/ResultScreen.js
Labels: 🚨 BugFix, 🖼 HTML&CSS

#33 🥃 fix : Social Btn css,URL 수정
  src/components/SocialComponents/Twitter.js
  src/components/SocialShare.js
  src/pages/Ppak.js
  src/pages/ResultScreen.js
Labels: 🖼 HTML&CSS

#36 🥃 fix : Social 수정
  src/pages/Ppak.js
  src/pages/ResultScreen.js
Labels: 🚨 BugFix

#37 🥃 fix : 카카오 공유 url 수정
  src/components/SocialComponents/Kakao.js
  src/components/SocialShare.js
Labels: 🚨 BugFix

#38 🥃 fix : 결과 페이지 공유 시 빈화면 현상 해결
  src/pages/Ppak.js
  src/pages/ResultScreen.js
Labels: 🚨 BugFix
